name: Release Image

on:
  workflow_dispatch:
    inputs:
      commit_sha: 
        description: 'RocketMQ Dashboard repo commit hash'
        required: false
        type: string
      force_release:
        description: 'Force release even if not updated'
        required: false
        type: boolean
  schedule:
    - cron: '0 6 * * *'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  REGISTRY: registry.cn-shanghai.aliyuncs.com
  IMAGE_NAME: eastcoal_cn/rocketmq-dashboard

permissions:
  actions: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dashboard repo
      uses: actions/checkout@v4
      with:
        repository: apache/rocketmq-dashboard
        ref: ${{ inputs.commit_sha || 'master' }}

    - name: Checkout current repo
      run: |
        git clone https://github.com/liuweiGL/rocketmq-dashboard-docker.git rocketmq-dashboard-docker
        cd rocketmq-dashboard-docker
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        cd ..

    - name: Check dashboard updated
      id: check_updated
      run: |
        current_hash=""
        latest_hash=$(git rev-parse HEAD)
        if [ -f rocketmq-dashboard-docker/hash ]; then
            current_hash=$(cat rocketmq-dashboard-docker/hash)
        fi
        if [ "$current_hash" == "$latest_hash" ]; then
            latest_hash=""
        else
            echo $latest_hash > rocketmq-dashboard-docker/hash
            dashboard_commit_msg=$(git log -1 --pretty=format:%B)
            cd rocketmq-dashboard-docker
            git add .
            git commit -m "update hash by: $dashboard_commit_msg"
            cd ..
        fi
        echo "result=$latest_hash" >> $GITHUB_OUTPUT
    
    - name: Cancel if not changed
      uses: andymckay/cancel-action@0.4
      if: steps.check_updated.outputs.result == '' && !inputs.force_release

    - name: Set up JDK 8 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        architecture: x64
        cache: maven

    - name: Run the Maven package
      run: |
        mvn -q -DskipTests clean package

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rocketmq-dashboard.jar
        path: '**/*.jar'
  
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    # https://github.com/docker/login-action
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Resolve Image Tag
      id: resolve_image_tag
      run: |
        commit_sha="${{ inputs.commit_sha }}"
        tag="latest"
        if [ -n "$commit_sha" ]; then
          tag="${commit_sha:0:7}"
        fi
        echo "result=$tag" >> $GITHUB_OUTPUT

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
      with:
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.resolve_image_tag.output.result }}
